version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: movieranker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "C:\Program Files\PostgreSQL\14\data"