# Generated by Django 4.1.5 on 2023-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierank',
            name='movie',
        ),
        migrations.AddField(
            model_name='movierank',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
